=== ningboliuwei/Course_XML/XmlReader与XmlWriter的使用/Docs/Book.xsd
<?xml version="1.0" encoding="gb2312"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:attribute name="isbn" type="xs:string"/>
	<!--<xs:attribute name="bookcategory" >
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:enumeration value="文艺"/>
			<xs:enumeration value="科学"/>
		</xs:restriction>
	</xs:simpleType>
</xs:attribute>-->
	<xs:simpleType name="gradeUnion">
		<xs:union>
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="0"/>
					<xs:maxInclusive value="100"/>
				</xs:restriction>
			</xs:simpleType>
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="优"/>
					<xs:enumeration value="良"/>
					<xs:enumeration value="及格"/>
					<xs:enumeration value="不及格"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:element name="book">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="xs:string"/>
				<!--<xs:element name="author" type="xs:string" default="佚名"/>-->
				<xs:element name="author" type="xs:string"/>
				<xs:element name="price" type="xs:float"/>
				<!--<xs:element name="price" type="xs:string"/>-->
				<xs:element name="resume" type="xs:string"/>
				<xs:element name="recommendation" type="xs:string"/>
				<xs:element name="publish" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="publisher" type="xs:string"/>
							<xs:element name="pubdate" type="xs:date"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute ref="isbn"/>
			<xs:attribute name="bookcategory">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="文艺"/>
						<xs:enumeration value="科学"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<!--<xs:attribute name="isbn" type="xs:string"/>-->
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ningboliuwei/Course_XML/XmlReader与XmlWriter的使用/Docs/Book.xml
<?xml version="1.0" encoding="gb2312"?>
<book isbn="0-764-58007-8" xsi:type="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Book.xsd">
	<title>三国演义</title>
	<author>罗贯中</author>
	<price>80.00</price>
	<resume>滚滚长江东逝水，浪花淘尽英雄。是非成败转头空：青山依旧在，几度夕阳红。白发渔樵江渚上，惯看秋月春风。一壶浊酒喜相逢：古今多少事，都付笑谈中。</resume>
	<recommendation>经典好书</recommendation>
	<publish>
		<publisher>文艺出版社</publisher>
		
	<!--<pubdate>1998-10-29</pubdate>-->
	</publish>
</book>
